### ISSUE TITLE
[Slides] Week5 having minor error in typing

### ISSUE THREAD

**Issue by lehoangh** [msramalho/Teach-Me-Quantum#2]
In Week5 about quantum algorithms, with slide 18, there is a minor tying here, which is shown in the image. 
![image](https://user-images.githubusercontent.com/23434461/61577322-7874dc00-ab18-11e9-95cf-d413a3ce09ad.png). Here, the yellow highlights have to (-1)^f|1>|1>. Also, in the solution of exercise in week5, why you did flip qubit? 
![image](https://user-images.githubusercontent.com/23434461/61577406-6a738b00-ab19-11e9-81a6-cb4173edbd39.png). I don't understand why you did that?

**Comment by msramalho** [comment]
Hey @lehoangh,

Thanks for the typo report on the slides, it has been fixed!

As for the qubit flip, that is in accordance with the algorithm's definition, you can check it [here](https://www.quantiki.org/wiki/deutsch-jozsa-algorithm) (4th paragraph).

Good luck 😉
